# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTqc8_5GHuG9gH4X6wa6gu66HUPg7MiH
"""

from google.colab import drive
drive.mount('/content/drive')

!cp -r /content/drive/MyDrive/FinalYear_Research/MonoPoly_Model/features /content/monopoly_data

FEATURE_ROOT = "/content/monopoly_data"

!ls /content/monopoly_data

!pip install torch torchvision torchaudio librosa numpy scikit-learn tqdm

# Load a single feature file to verify feature shape and consistency - uniform feature extraction

import numpy as np
sample = np.load(
    next(iter(
        __import__("pathlib").Path(FEATURE_ROOT + "/train/mono").glob("*.npy")
    ))
)
print(sample.shape) # (Mel bins, Time frames)

import torch
from torch.utils.data import Dataset
from pathlib import Path
import numpy as np

class MonoPolyDataset(Dataset):
    def __init__(self, root, split):
        self.files = []
        self.labels = []

        # Assign numeric labels to mono (0) and poly (1) classes
        for label, cls in enumerate(["mono", "poly"]):
            paths = Path(root, split, cls).glob("*.npy")
            for p in paths:
                self.files.append(p)
                self.labels.append(label)

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        x = np.load(self.files[idx]) # Load feature file
        x = torch.tensor(x, dtype=torch.float32).unsqueeze(0) # Convert to tensor and add channel dimension for CNN input
        y = torch.tensor(self.labels[idx], dtype=torch.long) # Load class label
        return x, y

from torch.utils.data import DataLoader

train_ds = MonoPolyDataset(FEATURE_ROOT, "train")
val_ds   = MonoPolyDataset(FEATURE_ROOT, "val")
test_ds  = MonoPolyDataset(FEATURE_ROOT, "test")

train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_ds, batch_size=32)
test_loader  = DataLoader(test_ds, batch_size=32)

print(len(train_ds), len(val_ds), len(test_ds))

def count(split):
    mono = len(list(Path(FEATURE_ROOT, split, "mono").glob("*.npy")))
    poly = len(list(Path(FEATURE_ROOT, split, "poly").glob("*.npy")))
    return mono, poly, mono + poly

for s in ["train", "val", "test"]:
    print(s, count(s))

from pathlib import Path

def find_extra_poly(split, expected_poly_count):
    poly_dir = Path(FEATURE_ROOT, split, "poly")
    poly_files = sorted(poly_dir.glob("*.npy"))

    if len(poly_files) <= expected_poly_count:
        print(f"{split}: No extra poly files")
        return []

    extra = poly_files[expected_poly_count:]
    print(f"{split}: {len(extra)} extra poly files found")
    for f in extra[:5]:
        print("  ", f.name)
    return extra


extra_train_poly = find_extra_poly("train", expected_poly_count=15400)
extra_test_poly  = find_extra_poly("test",  expected_poly_count=3300)

# delete extra train poly
for f in extra_train_poly:
    f.unlink()

# delete extra test poly
for f in extra_test_poly:
    f.unlink()

print("Extra poly files deleted successfully")

for s in ["train", "val", "test"]:
    print(s, count(s))

import torch.nn as nn

class CRNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.cnn = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d((2, 2)),

            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d((2, 2))
        )

        self.gru = nn.GRU(
            input_size=64 * 32,
            hidden_size=128,
            batch_first=True,
            bidirectional=True
        )

        self.fc = nn.Linear(256, 2)

    def forward(self, x):
        x = self.cnn(x)               # (B, C, F, T)
        x = x.permute(0, 3, 1, 2)     # (B, T, C, F)
        x = x.flatten(2)              # (B, T, C*F)
        x, _ = self.gru(x)
        x = x.mean(dim=1)
        return self.fc(x)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = CRNN().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

from tqdm import tqdm

def train_epoch(loader):
    model.train()
    total_loss, correct = 0, 0

    for x, y in tqdm(loader):
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        correct += (out.argmax(1) == y).sum().item()

    return total_loss / len(loader), correct / len(loader.dataset)

def eval_epoch(loader):
    model.eval()
    correct = 0

    with torch.no_grad():
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            correct += (out.argmax(1) == y).sum().item()

    return correct / len(loader.dataset)

EPOCHS = 20

for epoch in range(EPOCHS):
    loss, acc = train_epoch(train_loader)
    val_acc = eval_epoch(val_loader)

    print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {loss:.4f} | Train Acc: {acc:.3f} | Val Acc: {val_acc:.3f}")

test_acc = eval_epoch(test_loader)
print(f"Test Accuracy: {test_acc:.3f}")

from sklearn.metrics import confusion_matrix
import numpy as np

y_true, y_pred = [], []

model.eval()
with torch.no_grad():
    for x, y in test_loader:
        out = model(x.to(device))
        y_true.extend(y.numpy())
        y_pred.extend(out.argmax(1).cpu().numpy())

print(confusion_matrix(y_true, y_pred))

from sklearn.metrics import classification_report

print(classification_report(
    y_true, y_pred,
    target_names=["Monophonic", "Polyphonic"]
))

import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=["Mono", "Poly"],
            yticklabels=["Mono", "Poly"])
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix – CRNN Mono/Poly Classifier")
plt.show()

train_accs, val_accs = [], []

for epoch in range(EPOCHS):
    loss, acc = train_epoch(train_loader)
    val_acc = eval_epoch(val_loader)

    train_accs.append(acc)
    val_accs.append(val_acc)

plt.plot(train_accs, label="Train Accuracy")
plt.plot(val_accs, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.title("Training vs Validation Accuracy")
plt.show()

from sklearn.metrics import roc_curve, auc

probs = []

model.eval()
with torch.no_grad():
    for x, _ in test_loader:
        out = model(x.to(device))
        probs.extend(torch.softmax(out, dim=1)[:,1].cpu().numpy())

fpr, tpr, _ = roc_curve(y_true, probs)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0,1], [0,1], '--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve – Mono vs Poly")
plt.legend()
plt.show()

torch.save(model.state_dict(), "mono_poly_crnn_new.pth")

from google.colab import files
files.download("mono_poly_crnn_new.pth")

